name: CI AgroKit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar lint
        run: npm run lint --if-present

      - name: Ejecutar pruebas
        run: npm test --if-present

      - name: Construir proyecto
        run: npm run build
